### ISSUE TITLE
Dodati kontroler i view za stranicu o glagoljici.

### ISSUE THREAD

**Issue by knezmilos13** [knezmilos13/glagoljator#5]
Dodati kontroler i view za stranicu o glagoljici. Za sada na toj stranici moze da pise samo njeno ime ili tako nesto, dok se dogovorimo koji ce konkretni sadrzaji biti tu. Ovde cemo otom potom staviti sadrzaje sa wikipedije i drugih izvora, linkove, itd. i verovatno cemo rasturiti ovu jednu stranicu na vise njih, ali za sada neka ide kao jedan kontroler - jedan view.

**Comment by DamjanZ** [comment]
Odrađeno. Posle će stranica biti dopunjena.
